FROM python:3.6.7-slim
MAINTAINER seongwonhan88@gmail.com

RUN apt-get -y update
RUN apt-get -y dist-upgrade
RUN apt-get -y install gcc nginx supervisor && \
    pip3 install uwsgi && \
    apt -y remove gcc && \
    apt -y autoremove

COPY requirements_production.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt

