# Generated by Django 2.1.3 on 2018-11-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_saved_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_room',
            field=models.ManyToManyField(related_name='saved_user', to='home.Room'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_introduction',
            field=models.TextField(blank=True),
        ),
    ]
