# Generated by Django 2.1.3 on 2018-11-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_img_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_introduction',
            field=models.TextField(default='hello world'),
            preserve_default=False,
        ),
    ]
