# Generated by Django 2.1.3 on 2018-11-24 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('help_text', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_guest', models.IntegerField()),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('reserved_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostThumbnailImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_thumbnail_url', models.ImageField(blank=True, null=True, upload_to='pictures/host/')),
                ('host_thumbnail_url_small', models.ImageField(blank=True, null=True, upload_to='pictures/host/')),
            ],
        ),
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_info_1', models.TextField()),
                ('home_info_2', models.TextField()),
                ('home_info_3', models.TextField()),
                ('home_info_4', models.TextField()),
                ('home_info_5', models.TextField()),
                ('photo1', models.ImageField(upload_to='picture/host/listing/')),
                ('photo2', models.ImageField(upload_to='picture/host/listing/')),
                ('photo3', models.ImageField(upload_to='picture/host/listing/')),
                ('photo4', models.ImageField(upload_to='picture/host/listing/')),
                ('photo5', models.ImageField(upload_to='picture/host/listing/')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathrooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('person_capacity', models.IntegerField()),
                ('room_name', models.CharField(max_length=100)),
                ('room_type', models.CharField(max_length=20)),
                ('room_and_property_type', models.CharField(max_length=20)),
                ('public_address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(to='home.Amenity')),
            ],
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_info', to='home.Room'),
        ),
        migrations.AddField(
            model_name='hostthumbnailimg',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_thumbnails', to='home.Room'),
        ),
    ]
