# Generated by Django 2.1.3 on 2018-11-26 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('help_text', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_guest', models.IntegerField()),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('reserved_date', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathrooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('person_capacity', models.IntegerField()),
                ('room_name', models.CharField(max_length=100)),
                ('room_type', models.CharField(max_length=20)),
                ('room_and_property_type', models.CharField(max_length=20)),
                ('public_address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostImages',
            fields=[
                ('host_images', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.Room')),
                ('host_thumbnail_url', models.ImageField(blank=True, null=True, upload_to='pictures/host/')),
                ('host_thumbnail_url_small', models.ImageField(blank=True, null=True, upload_to='pictures/host/')),
            ],
        ),
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('room_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.Room')),
                ('room_info_1', models.TextField()),
                ('room_info_2', models.TextField()),
                ('room_info_3', models.TextField()),
                ('room_info_4', models.TextField()),
                ('room_photo_1', models.ImageField(upload_to='picture/host/listing/')),
                ('room_photo_2', models.ImageField(upload_to='picture/host/listing/')),
                ('room_photo_3', models.ImageField(upload_to='picture/host/listing/')),
                ('room_photo_4', models.ImageField(upload_to='picture/host/listing/')),
                ('room_photo_5', models.ImageField(upload_to='picture/host/listing/')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(to='home.Amenity'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_info', to='home.Room'),
        ),
    ]
