# Generated by Django 2.1.3 on 2018-12-08 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bookings',
            field=models.ManyToManyField(through='home.Booking', to='members.NormalUser'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listed_room', to='members.HostUser'),
        ),
        migrations.AddField(
            model_name='review',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.NormalUser'),
        ),
        migrations.AddField(
            model_name='review',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Room'),
        ),
        migrations.AddField(
            model_name='bookingdates',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_dates', to='home.Booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.NormalUser'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_info', to='home.Room'),
        ),
    ]
