# Generated by Django 2.1.3 on 2018-11-29 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_date', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_date', to='home.Room')),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='reserved_date',
            new_name='created_date',
        ),
    ]
