# Generated by Django 2.1.3 on 2018-11-30 03:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20181129_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bookings',
            field=models.ManyToManyField(through='home.Booking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingdate',
            name='reserved_date',
            field=models.DateField(unique=True),
        ),
    ]
