# Generated by Django 2.1.3 on 2018-12-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181208_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='public_address',
            field=models.CharField(max_length=100),
        ),
    ]
