# Generated by Django 2.1.3 on 2018-12-01 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181130_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdate',
            name='room',
        ),
        migrations.AddField(
            model_name='bookingdate',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_date', to='home.Booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingdate',
            name='reserved_date',
            field=models.DateField(),
        ),
    ]
