# Generated by Django 2.1.3 on 2018-12-12 11:32

import django.core.validators
from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181210_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), rest_framework.compat.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='rate_average',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
