# Generated by Django 2.1.3 on 2018-12-03 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181201_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdate',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_dates', to='home.Booking'),
        ),
    ]
