# Generated by Django 2.1.3 on 2018-12-04 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181203_2112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingDate',
            new_name='BookingDates',
        ),
    ]
